kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "v": "5"
        "runtime-config": "admissionregistration.k8s.io/v1beta1=true"
        "feature-gates": "MutatingAdmissionPolicy=true"
